---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-deployment-1
  labels:
    app: fabric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-1
  template:
    metadata:
      labels:
        app: service-1
    spec:
      containers:
      - name: service-1
        image: nitinkubernetes/fabric-service-1
        ports:
        - containerPort: 8080
---        
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-deployment-2
  labels:
    app: fabric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
    spec:
      containers:
      - name: service-2
        image: nitinkubernetes/fabric-service-2
        ports:
        - containerPort: 8080

---       
apiVersion: v1
kind: Service
metadata:
  name: fabric-service-1
spec:
  type: NodePort
  selector:
    app: service-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---      
apiVersion: v1
kind: Service
metadata:
  name: fabric-service-2
spec:
  type: NodePort
  selector:
    app: service-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080