apiVersion: v1
kind: ServiceAccount
metadata:
  name: fabric-user
  namespace: fabric
secrets:
- name: default-secret  
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fabric-admin
  namespace: fabric
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-view
  namespace: fabric
subjects:
- kind: ServiceAccount
  name: fabric-user
  namespace: fabric
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fabric-admin